[build]
    functions = "functions"
    # command = "netlify-lambda install"

[functions]
    external_node_modules = ["import-fresh"]

[[redirects]]
  from = "https://ogextractor.netlify.app/"
  to = "https://github.com/ARogueOtaku/og-tag-extractor"
  status = 301
  force = true