[build]
    functions = "functions"
    # command = "netlify-lambda install"

[functions]
    external_node_modules = ["import-fresh"]

[[redirects]]
  from = "/"
  to = "https://github.com/ARogueOtaku/og-tag-extractor"
  status = 301
  force = true

[[redirects]]
  from = "/extract"
  to = "/.netlify/functions/ogExtractionHandler"
  status = 301
  force = true